ComparAcademyTask/Controllers/LoginController.cs
using BusinessLayer.Managers;
using ComparAcademyTask.Models;
using DataAccessLayer.Security;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;


namespace ComparAcademyTask.Controllers
{
    public class LoginController : Controller
    {
        private UserManager db;
        public LoginController(UserManager db)
        {
            this.db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(User entity)
        {

            var user = db.GetAll().FirstOrDefault(x => x.Email == entity.Email && x.Password == Utils.PasswordHash(entity.Password));

            if (user != null)
            {
                List<Claim> claims = new List<Claim>()
                {
                    new Claim("Email",user.Email),
                    new Claim("Name",user.Name),
                    new Claim("ID",user.ID.ToString())
                };
                 
                ClaimsIdentity indentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new ClaimsPrincipal(indentity);
                await HttpContext.SignInAsync(principal);

                HttpContext.Session.SetString("ID", user.ID.ToString());
                HttpContext.Session.SetString("Name", user.Name.ToString());

                UserModel.Name = HttpContext.Session.GetString("Name");






                return RedirectToAction("Index", "MyPost");
            }
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");


        }

        public IActionResult test()
        {

            return View();
        }
    }
}

ComparAcademyTask/Controllers/SharedPostController.cs
using BusinessLayer.Managers;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ComparAcademyTask.Controllers
{
    public class SharedPostController : Controller
    {
        private ShareManager db_share;
        private UserManager db_user;
        public SharedPostController(ShareManager db_share, UserManager db_user)
        {
            this.db_share = db_share;
            this.db_user = db_user;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var values = db_share.GetWithPostAndUser(Convert.ToInt32(HttpContext.Session.GetString("ID")));
            return View(values);
        }

        public IActionResult Delete(int id)
        {
            var entity = db_share.GetById(id);
            db_share.Delete(entity);

            return RedirectToAction("Index");
        }

        public IActionResult Share(string email, int id)
        {

            var recipient = db_user.GetAll().FirstOrDefault(x => x.Email == email);
            if (recipient == null)
            {
                TempData["Exception"] = "Bu email-ə uyğun istifadəçi yoxdur.";
                TempData["ID"] = id;
            }
            else
            {
                Share entity = new Share()
                {
                    PostID = id,
                    SenderID = Convert.ToInt32(HttpContext.Session.GetString("ID")),
                    RecipientID = recipient.ID
                };

                db_share.Add(entity);
            }

            return RedirectToAction("Index", "MyPost");
        }

        public async Task<IActionResult> DownloadFile(string filePath)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Photos", filePath);
            var memory = new MemoryStream();

            try
            {
                using (var stream = new FileStream(path, FileMode.Open))
                {

                    await stream.CopyToAsync(memory);
                }

            }
            catch (Exception)
            {
            }

            memory.Position = 0;
            var contentType = "APPLICATION/octet-stream";
            var fileName = Path.GetFileName(path);

            return File(memory, contentType, fileName);
        }
    }
}

ComparAcademyTask/Views/PartialViews/Header.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="MyPost" asp-action="Index">
                        Postlarım
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="SharedPost" asp-action="Index">Paylaşılanlar</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Login" asp-action="LogOut">Çıxış</a>
                </li>
            </ul>
        </div>
    </nav>

</div>

ComparAcademyTask/Views/PartialViews/WelcomeBack.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span style="font-size:15px">Xoş gəlmişsiniz!</span>
</div>